[project]
name = "powercalc"
version = "0.2.0-beta.1"
description = "Accessible professional desktop calculator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.10.0",
    "sympy>=1.14.0",
    "wxpython>=4.2.5",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "pytest>=9.1.1",
    "ruff>=0.15.16",
]

[tool.ruff]
line-length = 80

[tool.ruff.format]
indent-style = "tab"
line-ending = "lf"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501"]
ignore = [
	# indentation contains tabs
	"W191",
]
